output_directory = "_out"
title = "Sneaky Crow"
subtitle = "software wizard"
motd = "Great fontstacks that don't require downloads"
motd_sub = "modernfontstacks.com"
motd_link = "https://modernfontstacks.com/"

# Requires GitHub personal access token for private projects
github_projects = [
    { repository = "sneakycrow/fulcrum" },
    { repository = "sneakycrow/cobrashare" },
    { repository = "sneakycrow/chats-controller" },
    { repository = "sneakycrow/izfs" },
]

# Uncomment this line and modify the example to be the first one to add yourself
#boosts = [
#    { name = "Baz Qux", keywords = ["front-end", "back-end", "react", "node"], email = "bazqux@example.com", url = "https://example.com/bazqux" }
#]