output_directory = "_out"
title = "Sneaky Crow"
subtitle = "software wizard"
motd = "A super modern file system. The cli has a funny name for the default binary"
motd_sub = "seaweedfs"
motd_link = "https://github.com/seaweedfs/seaweedfs"

# Requires GitHub personal access token for private projects
github_projects = [
    { repository = "sneakycrow/fulcrum" },
    { repository = "sneakycrow/cobrashare" },
    { repository = "sneakycrow/chats-controller" },
    { repository = "sneakycrow/izfs" },
]

# Uncomment this line and modify the example to be the first one to add yourself
#boosts = [
#    { name = "Baz Qux", keywords = ["front-end", "back-end", "react", "node"], email = "bazqux@example.com", url = "https://example.com/bazqux" }
#]
