output_directory = "_out"
title = "Zachary Sohovich"
subtitle = "software wizard"

# Requires GitHub personal access token for private projects
github_projects = ["sneakycrow/fulcrum", "sneakycrow/cobrashare"]

boosts = [
    { name = "Baz Qux", keywords = ["front-end", "back-end", "react", "node"], email = "bazqux@example.com", url = "https://example.com/bazqux" }
]