# fly.toml app configuration file generated for sneakycrow-dev on 2023-07-15T15:40:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sneakycrow-dev"
primary_region = "sea"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1

[[vm]]
size = "shared-cpu-2x"
memory = "2gb"
