import type { NextPage } from "next";
import Head from "next/head";
import { Box, Button, Container, Image, Text } from "@mantine/core";
import { signIn, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <Container fluid>
      <Head>
        <title>web and data developer - sneaky crow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!session && <Button onClick={() => signIn("github")}>Sign in</Button>}
        <Box sx={{ width: 400 }}>
          <Image
            src="/logo.svg"
            fit="contain"
            alt="A line art graphic of a crow with a green baseball cap on"
            withPlaceholder
            placeholder={
              <Text>
                A line art graphic of a crow with a green baseball cap on
              </Text>
            }
          />
        </Box>

        <h1>sneaky crow</h1>

        <h2>data and web developer</h2>

        <h3>about me</h3>

        <p>
          My name is <strong>Zach</strong> and I love problem-solving with
          software. With over a decade of experience, &apos; worked with many
          partners including{" "}
          <strong>Twitch, Nike, and local PNW businesses</strong>. I work with
          both businesses and individuals.
        </p>

        <p>
          Some of my favorite technologies to work with are:{" "}
          <strong>
            Rust, Go, React, AI, CI/CD, Data Analysis, Data Pipelining...
          </strong>
        </p>

        <p>
          If you have an interesting project idea or would like to work with me
          then <a href="mailto:zach@sneakycrow.dev">[contact me vial email]</a>
        </p>
      </main>
    </Container>
  );
};

export default Home
