apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production
nameSuffix: -production

resources:
  - ../../base/ui
  - ingress.yaml

images:
  - name: ui

labels:
  - includeSelectors: true
    pairs:
      environment: production
