name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ github.repository }}
          enableBuildKit: true
          addTimestamp: true
          pushImage: false
