name: Code Coverage
on: [push]

jobs:
  build:
    name: Run Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
