name: "build and deploy"

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_deploy:
    environment: production
    name: build and deploy image
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install doctl
        uses: digitalocean/action-doctl@v2.4.1
        with:
          token: ${{ secrets.DO_ACCESS_KEY }}

      - name: Build container image
        run: docker build -t ${{ secrets.REGISTRY }}/${{ github.repository }}:$(echo $GITHUB_SHA | head -c7) -t ${{ secrets.REGISTRY }}/${{ github.repository }}:latest .

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.REGISTRY }}/${{ github.repository }} --all-tags