name: build and upload website
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build website
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: upload
        uses: reggionick/s3-deploy@v3
        with:
          folder: _out
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_REGION }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /*
          delete-removed: true
          no-cache: true
          private: true
          filesToInclude: ".*/*,*/*,**"