# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: deploy

on:
  workflow_call:
    inputs:
      namespace:
        type: string
        required: true
        description: "namespace to deploy to"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      push: true

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.namespace }}
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_REGISTRY_KEY }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ vars.CLUSTER_NAME }}

      - name: Update kustomization
        run: |
          cd k8s/overlays/${{ inputs.namespace }}
          kustomize edit set image ui=${{ secrets.DO_REGISTRY }}/${{ vars.UI_IMAGE }}:${{ needs.build.outputs.image_tag }}

      - name: Deploy to ${{ inputs.namespace }}
        run: |
          kubectl apply -k k8s/overlays/${{ inputs.namespace }}
          kubectl rollout status deployment/sneakycrow-${{ inputs.namespace }} -n ${{ inputs.namespace }} --timeout=2m
